# New ports collection makefile for:	mere-utils
# Version required:    	0.0.0.1b
# Date created:        	30 October 2019
# Whom:			Bhuiyan Mohammad Iklash<bhuiyan.mohammad.iklash@gmail.com>                
#
# $FreeBSD$
#

PORTNAME=       mere-utils
PORTVERSION=    0.0.1b
CATEGORIES=     devel
MASTER_SITES=	https://iklash@bitbucket.org/merelab/downlaods/mere-utils-lib-0.0.1b.tar.gz

MAINTAINER=     bhuiyan.mohammad.iklash@gmail.com
COMMENT=	Mere utility library for the mere software suite

LICENSE=     	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/COPYING

WRKSRC=         ${WRKDIR}/${PORTNAME}-${PORTVERSION}

.include <bsd.port.mk>
